import 'package:haircut_delivery/clientapp/models/client_app_shop.dart';

final List<ClientAppShop> clientAppShops = [
  ClientAppShop(
    shopId: 1,
    firstName: 'ฤทธิไกร',
    lastName: 'พงศ์',
    email: 'tudplern@gmail.com',
    address: 'แม่เหียะ ใกล้โรงเรียน สารสาสน์ วิเทศน์ลานนา',
    shopName: 'ตัดเพลิน',
    phone: '0966564293',
    latitude: 18.73602,
    longitude: 98.95441,
    avatarUrl: 'shop1.jpg',
    rating: 4.8,
    counting: 137,
  ),
  ClientAppShop(
    shopId: 2,
    firstName: 'นายยุทธโชติ',
    lastName: 'ช่วยชูกลิ่น',
    email: 'jareonhua@gmail.com.com',
    address: 'สันกำแพง (บ้านยวม)',
    shopName: 'เจริญหัว',
    phone: '0918546116',
    latitude: 18.75694,
    longitude: 99.04975,
    isApproved: true,
    avatarUrl: 'shop2.jpg',
    rating: 4.4,
    counting: 13,
  ),
  ClientAppShop(
    shopId: 3,
    firstName: 'พี่แนน',
    lastName: 'บาร์เบอร์โซน',
    email: 'tle@tle.com',
    address: 'ฟ้าฮ่าม หลัง แยกรวมโชค',
    shopName: 'บาร์เบอร์โซน',
    phone: '0918656162',
    latitude: 18.82474,
    longitude: 99.00675,
    isApproved: true,
    avatarUrl: 'shop3.jpg',
    rating: 4,
    counting: 20,
  ),
  ClientAppShop(
    shopId: 4,
    firstName: 'Worapong',
    lastName: 'Auefuephan',
    email: 'toonztudio@gmail.com',
    address: 'ร้านอยู่โซนสันติธรรม ถนนสันติสุข ข้างร้านขายยา',
    shopName: 'บาร์เบอร์ ครูว์',
    phone: '0808454381',
    latitude: 18.80377,
    longitude: 98.97429,
    isApproved: true,
    avatarUrl: 'shop4.jpg',
    rating: 5,
    counting: 15,
  ),
  ClientAppShop(
    shopId: 5,
    firstName: 'นายชัชวิสิทธิ์',
    lastName: 'จันทร์ธิมา',
    email: 'scotch.td@gmail.com',
    address: 'ร้านอยู่ใต้หอพักตึกขาว โซนเจ็ดยอด',
    shopName: 'ร็อบเบอร์ บาร์เบอร์',
    phone: '0993787333',
    latitude: 18.80766,
    longitude: 98.96469,
    isApproved: true,
    avatarUrl: 'shop5.jpg',
    rating: 4.1,
    counting: 100,
  ),
  ClientAppShop(
    shopId: 6,
    firstName: 'นายกิตินันท์',
    lastName: 'กวีกิจสุนทร',
    email: 'aaa@hotmail.com',
    address: 'ติด ขนส่ง อาเขต',
    shopName: 'คัท เอม ออน',
    phone: '0884088688',
    latitude: 18.79854,
    longitude: 99.01729,
    isApproved: true,
    avatarUrl: 'shop6.jpg',
    rating: 4,
    counting: 14,
  ),
  ClientAppShop(
    shopId: 7,
    firstName: 'บอย',
    lastName: 'บาร์เบอร์',
    email: 'santi.masiri@gmail.com',
    address: 'จอมทอง',
    shopName: 'บอย บาร์เบอร์',
    phone: '0904895133',
    latitude: 18.42454,
    longitude: 98.68148,
    isApproved: true,
    avatarUrl: 'shop7.jpg',
    rating: 4.2,
    counting: 13,
  ),
  ClientAppShop(
    shopId: 8,
    firstName: 'ฤทธิไกร',
    lastName: 'พงศ์ธิ',
    email: '13belovedd@gmail.com',
    address: 'หางดง ตรงข้ามวัดช่างคำน้อย',
    shopName: 'Yes\'sir Barber Shop',
    phone: '0966564293',
    latitude: 18.70102,
    longitude: 98.93124,
    isApproved: true,
    avatarUrl: 'shop8.jpg',
    rating: 3.8,
    counting: 37,
  ),
  ClientAppShop(
    shopId: 9,
    firstName: 'นายกิตติศักดิ์',
    lastName: 'คำไล',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่หลังมช. ใต้หอพัก',
    shopName: 'สะบายดีคัท',
    phone: '0861199187',
    latitude: 18.78906,
    longitude: 98.95507,
    isApproved: true,
    avatarUrl: 'shop9.jpg',
    rating: 4.0,
    counting: 109,
  ),
  ClientAppShop(
    shopId: 10,
    firstName: 'นายอมรฤทธิ์',
    lastName: 'บางวิเศษ',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่หลังราชภัฏ ข้างร้านลาบ',
    shopName: 'เอนคัท',
    phone: '0918518109',
    latitude: 18.80532,
    longitude: 98.9914,
    isApproved: true,
    avatarUrl: 'shop10.jpg',
    rating: 4.1,
    counting: 19,
  ),
  ClientAppShop(
    shopId: 11,
    firstName: 'นางวิไลพร',
    lastName: 'ทองสมาน',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนกาดสามแยก ในซอยหมู่บ้านชลดา',
    shopName: 'ร้านเสริมสวยไฮคลาส',
    phone: '0845454770',
    latitude: 18.79093,
    longitude: 98.95634,
    isApproved: true,
    avatarUrl: 'shop11.jpg',
    rating: 3.7,
    counting: 16,
  ),
  ClientAppShop(
    shopId: 11,
    firstName: 'นางวิไลพร',
    lastName: 'ทองสมาน',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนกาดสามแยก ในซอยหมู่บ้านชลดา',
    shopName: 'ร้านเสริมสวยไฮคลาส',
    phone: '0845454770',
    latitude: 18.79093,
    longitude: 98.95634,
    isApproved: true,
    avatarUrl: 'shop11.jpg',
    rating: 4.1,
    counting: 29,
  ),
  ClientAppShop(
    shopId: 12,
    firstName: 'นางเรศนภา',
    lastName: 'มโนคำ',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ดอยสะเก็ต',
    shopName: 'ร้านเพอร์เฟคอาย',
    phone: '0831704774',
    latitude: 18.74649,
    longitude: 99.11989,
    isApproved: true,
    avatarUrl: 'shop12.jpg',
    rating: 4.3,
    counting: 39,
  ),
  ClientAppShop(
    shopId: 13,
    firstName: 'ศิริอร (แอน)',
    lastName: 'กาสุยะ',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'หางดง ตลาดหางดง',
    shopName: 'ร้านตัดเพลิน เสริมสวย ทำเล็บ',
    phone: '0966564293',
    latitude: 18.68981,
    longitude: 98.92165,
    isApproved: true,
    avatarUrl: 'shop13.jpg',
    rating: 4.0,
    counting: 29,
  ),
  ClientAppShop(
    shopId: 14,
    firstName: 'นางอารีย์',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่หลังวัดพระสิงห์ ถนนอารักษ์ ซอย5',
    shopName: 'ร้านเสริมสวยอารีย์',
    phone: '053416423',
    latitude: 18.78964,
    longitude: 98.97972,
    isApproved: true,
    avatarUrl: 'shop14.jpg',
    rating: 3.8,
    counting: 19,
  ),
  ClientAppShop(
    shopId: 15,
    firstName: 'นางสาวพชรพร',
    lastName: 'ทรัพย์มหาสกุล',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ในโครงการสตาร์อเวนิว รวมโชค',
    shopName: 'ร้านเสริมสวยหลินบิ้วตี้ซาลอน',
    phone: '-',
    latitude: 18.82955,
    longitude: 99.01245,
    isApproved: true,
    avatarUrl: 'shop15.jpg',
    rating: 4.2,
    counting: 26,
  ),
  ClientAppShop(
    shopId: 16,
    firstName: 'คุณแอ้ว',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนพิงค์ดอย ข้างโรงงานผลิตเส้นหมี่',
    shopName: 'ร้านเสริมสวยแอ๊วซี่บิ้วตี้',
    phone: '0839440199',
    latitude: 18.86281,
    longitude: 98.98515,
    isApproved: true,
    avatarUrl: 'shop16.jpg',
    rating: 4.1,
    counting: 16,
  ),
  ClientAppShop(
    shopId: 17,
    firstName: 'คุณ แอน',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนกาดสามแยก ในหมู่บ้านลากูนน่า',
    shopName: 'ร้านเสริมสวยแอนบิ้วตี้ซาลอน',
    phone: '0988139613',
    latitude: 18.8305,
    longitude: 99.02786,
    isApproved: true,
    avatarUrl: 'shop17.jpg',
    rating: 3.8,
    counting: 26,
  ),
  ClientAppShop(
    shopId: 18,
    firstName: 'นางสาวธารทอง',
    lastName: 'สุวรรณ์',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนกาดสามแยกในซอยชิเชโด้',
    shopName: 'ร้านเสริมสวยคิตตี้ซาลอน',
    phone: '0892656970',
    latitude: 18.80311,
    longitude: 98.97735,
    isApproved: true,
    avatarUrl: 'shop18.jpg',
    rating: 3.6,
    counting: 22,
  ),
  ClientAppShop(
    shopId: 19,
    firstName: 'นางสาวภูศิตา',
    lastName: 'แก้วเรือง',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ตรงข้ามโรพยาบาลช้างเผือก',
    shopName: 'ร้านภูแฮร์คัทแอนด์บิ้วตี้ซาลอน',
    phone: '0946969516',
    latitude: 18.79847,
    longitude: 98.98694,
    isApproved: true,
    avatarUrl: 'shop19.jpg',
    rating: 3.9,
    counting: 24,
  ),
  ClientAppShop(
    shopId: 20,
    firstName: 'คุณเก๋',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนกาดสามแยก ข้างร้านก้อยบาร์เบอร์',
    shopName: 'ร้านกู๊ดเก๋ซาลอน',
    phone: '0905486805',
    latitude: 18.82558,
    longitude: 99.02131,
    isApproved: true,
    avatarUrl: 'shop20.jpg',
    rating: 3.9,
    counting: 24,
  ),
  ClientAppShop(
    shopId: 21,
    firstName: 'คุณแนน',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ดอนจั่น',
    shopName: 'The nail school ดอนจั่น',
    phone: '0905692364',
    latitude: 18.76835,
    longitude: 99.03082,
    isApproved: true,
    avatarUrl: 'shop21.jpg',
    rating: 4.0,
    counting: 14,
  ),
  ClientAppShop(
    shopId: 22,
    firstName: 'เรนโบ',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'คันคลอง ถ. คันคลองชลประทาน (ปากทางเข้าสิบสองปันนา)',
    shopName: 'ร้านเรนโบเนล 1',
    phone: '0857248989',
    latitude: 18.78383,
    longitude: 98.95802,
    isApproved: true,
    avatarUrl: 'shop22.png',
    rating: 4.1,
    counting: 15,
  ),
  ClientAppShop(
    shopId: 23,
    firstName: 'นางสาวยุวดี',
    lastName: 'วิเศษสุข',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนสันติธรรม ถนนสันติสุข ติดร้านเสริมสวยผ่องศรี',
    shopName: 'ร้านวิ้งวิ้งเนล',
    phone: '0650539947',
    latitude: 18.80324,
    longitude: 98.97681,
    isApproved: true,
    avatarUrl: 'shop23.png',
    rating: 3.9,
    counting: 15,
  ),
  ClientAppShop(
    shopId: 24,
    firstName: 'ชมพู่',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'กาดแม่เหียะ',
    shopName: 'ร้านเวรี่เนล',
    phone: '0815311169',
    latitude: 18.74799,
    longitude: 98.94161,
    isApproved: true,
    avatarUrl: 'shop24.jpg',
    rating: 4.5,
    counting: 35,
  ),
  ClientAppShop(
    shopId: 25,
    firstName: 'Aun',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'กาดแม่เหียะ',
    shopName: 'ร้านทำเล็บ Aun Nail Studio',
    phone: '0946294691',
    latitude: 18.78968,
    longitude: 98.97871,
    isApproved: true,
    avatarUrl: 'shop25.jpg',
    rating: 4.2,
    counting: 25,
  ),
  ClientAppShop(
    shopId: 26,
    firstName: 'นางสาวอารยา',
    lastName: 'นามสิงห์',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ใต้หอพักแฟมิลี่ ถนนอารักษ์ ซอย5',
    shopName: 'ร้านทำเล็บnataon nail,spa',
    phone: '0946294691',
    latitude: 18.78968,
    longitude: 98.97871,
    isApproved: true,
    avatarUrl: 'shop26.jpg',
    rating: 4.3,
    counting: 25,
  ),
  ClientAppShop(
    shopId: 27,
    firstName: 'เจนนี่',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนสันติธรรม ตรงข้ามวิวดอยเพลส',
    shopName: 'ร้านทำเล็บจอยเนล',
    phone: '0839233821',
    latitude: 18.80245,
    longitude: 98.97862,
    isApproved: true,
    avatarUrl: 'shop27.jpg',
    rating: 4.0,
    counting: 21,
  ),
  ClientAppShop(
    shopId: 28,
    firstName: 'แนน',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ถนนหัสดิเสวี',
    shopName: 'ร้าน Meridian nails',
    phone: '0948074544',
    latitude: 18.8026,
    longitude: 98.97876,
    isApproved: true,
    avatarUrl: 'shop28.jpg',
    rating: 4.2,
    counting: 21,
  ),
  ClientAppShop(
    shopId: 29,
    firstName: 'ปีโป้',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนสันติธรรม ซอยสันติสุข ติดร้านแต่งหน้าเจ้าสาว',
    shopName: 'ร้าน eepepo nails',
    phone: '0932136936',
    latitude: 18.80332,
    longitude: 98.97845,
    isApproved: true,
    avatarUrl: 'shop29.jpg',
    rating: 4.3,
    counting: 20,
  ),
  ClientAppShop(
    shopId: 30,
    firstName: 'ฟ้า',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่หลังมช. ใต้หอพักไพพนา',
    shopName: 'ร้านลัคกี้เนล',
    phone: '-',
    latitude: 18.77463,
    longitude: 98.99827,
    isApproved: true,
    avatarUrl: 'shop30.jpg',
    rating: 4.2,
    counting: 25,
  ),
  ClientAppShop(
    shopId: 31,
    firstName: 'นายรุ่งโรจน์',
    lastName: 'คำมาเรือน',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ถนนสามล้าน ซอย3',
    shopName: 'ร้านนวดเอวามาสสาจ',
    phone: '0835667794',
    latitude: 18.7848,
    longitude: 98.98129,
    isApproved: true,
    avatarUrl: 'shop31.jpg',
    rating: 4.3,
    counting: 20,
  ),
  ClientAppShop(
    shopId: 32,
    firstName: 'นุดี',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ถนนมรกต โซนสันติธรรม ติดร้านตัดผมชายลูกทุ่ง',
    shopName: 'ร้านนุดีนวดแผนไทย',
    phone: '0923851979',
    latitude: 18.80123,
    longitude: 98.98214,
    isApproved: true,
    avatarUrl: 'shop32.jpg',
    rating: 4.1,
    counting: 20,
  ),
  ClientAppShop(
    shopId: 33,
    firstName: 'นางนิภา',
    lastName: 'บายบิลตัน',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ถนนศรีดอนไชย',
    shopName: 'ร้านพุดตาลนวดเพื่อสุขภาพ',
    phone: '0943524592',
    latitude: 18.7811,
    longitude: 99.00025,
    isApproved: true,
    avatarUrl: 'shop33.jpg',
    rating: 4.0,
    counting: 22,
  ),
  ClientAppShop(
    shopId: 34,
    firstName: 'นางนิภา',
    lastName: 'บายบิลตัน',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่หลังศิลาสปา ถนนราชวิถี ซอย 1',
    shopName: 'ร้านบ้านเฮานวดแผนไทย',
    phone: '0979184311',
    latitude: 18.79062,
    longitude: 98.99272,
    isApproved: true,
    avatarUrl: 'shop34.jpg',
    rating: 4.2,
    counting: 23,
  ),
  ClientAppShop(
    shopId: 35,
    firstName: 'นางนิภา',
    lastName: 'บายบิลตัน',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่โซนสันติธรรม แถวคิวไอเกรสเฮ้าส์',
    shopName: 'ร้านแฮปปี้มาสสาจ',
    phone: '0617982039',
    latitude: 18.80132,
    longitude: 98.9758,
    isApproved: true,
    avatarUrl: 'shop35.jpg',
    rating: 4.1,
    counting: 21,
  ),
  ClientAppShop(
    shopId: 36,
    firstName: 'นางนิภา',
    lastName: 'บายบิลตัน',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ตรงข้ามออฟฟิสการบินไทย ถนนพระปกเกล้า',
    shopName: 'ร้านมาสสาจแอทเชียงใหม่',
    phone: '0646284495',
    latitude: 18.79324,
    longitude: 98.98754,
    isApproved: true,
    avatarUrl: 'shop36.jpg',
    rating: 4.1,
    counting: 21,
  ),
  ClientAppShop(
    shopId: 37,
    firstName: 'ศิลา',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ถนนราชวิถี ติดร้านวัตสัน สาขาศรีภูมิ',
    shopName: 'ร้านศิลาสปา',
    phone: '053222288',
    latitude: 18.79062,
    longitude: 98.99272,
    isApproved: true,
    avatarUrl: 'shop37.jpg',
    rating: 4.2,
    counting: 23,
  ),
  ClientAppShop(
    shopId: 38,
    firstName: 'นางนพลักษณ์',
    lastName: 'นิธิกาญจนพัฒน์',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู้ในซอย ถนนระแกง ซอย1',
    shopName: 'ร้านทาทองนวดเพื่อสุขภาพ',
    phone: '0811123998',
    latitude: 18.78018,
    longitude: 98.99259,
    isApproved: true,
    avatarUrl: 'shop38.jpg',
    rating: 4.5,
    counting: 23,
  ),
  ClientAppShop(
    shopId: 39,
    firstName: 'ปาริชาติ',
    lastName: 'พรมสิงห์',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ตรงข้ามโอเอซิสสปา',
    shopName: 'ร้านปาริชมาสสาจ',
    phone: '0636697855',
    latitude: 18.78723,
    longitude: 98.98239,
    isApproved: true,
    avatarUrl: 'shop39.jpg',
    rating: 4.5,
    counting: 20,
  ),
  ClientAppShop(
    shopId: 40,
    firstName: 'ลานนา',
    lastName: '-',
    email: 'nitipong.npdesigns@gmail.com',
    address: 'ร้านอยู่ฝั่งตรงข้ามสถานีตำรวจ ถนนจ่าบ้าน',
    shopName: 'ร้านบ้านไทยลานนา นวดเพื่อสุขภาพ',
    phone: '0873047335',
    latitude: 18.78892,
    longitude: 98.98558,
    isApproved: true,
    avatarUrl: 'shop40.jpg',
    rating: 4.1,
    counting: 22,
  ),
];
