import 'package:haircut_delivery/model/client_app_service.dart';

final List<ClientAppService> clientAppServices = [
  ClientAppService(
    serviceId: 1,
    serviceName: 'ตัดผมชาย',
    shopId: 1,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: true,
    price: 200,
    discount: 10,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 2,
    serviceName: 'ตัดผมเด็กชาย',
    shopId: 1,
    serviceCategoryId: 99,
    parentCatId: 97,
    isPartner: true,
    price: 200,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 3,
    serviceName: 'โกนหนวด',
    shopId: 1,
    serviceCategoryId: 98,
    parentCatId: 97,
    isPartner: true,
    price: 100,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 4,
    serviceName: 'ตัดผมเด็กชาย',
    shopId: 2,
    serviceCategoryId: 99,
    parentCatId: 97,
    isPartner: true,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 5,
    serviceName: 'ตัดผม แกะลายผม',
    shopId: 2,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: true,
    price: 350,
    deliveryPrice: 400,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 6,
    serviceName: 'โกนหนวด',
    shopId: 3,
    serviceCategoryId: 98,
    parentCatId: 97,
    isPartner: true,
    price: 100,
    deliveryPrice: 150,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 7,
    serviceName: 'ตัดผมชาย',
    shopId: 3,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: true,
    price: 2500,
    deliveryPrice: 200,
    discount: 50,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 8,
    serviceName: 'ตัดผมชาย',
    shopId: 4,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: true,
    price: 300,
    deliveryPrice: 400,
    discount: 50,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 9,
    serviceName: 'ตัดผมเด็กชาย',
    shopId: 4,
    serviceCategoryId: 99,
    parentCatId: 97,
    isPartner: false,
    price: 150,
    deliveryPrice: 200,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 10,
    serviceName: 'โกนหนวด',
    shopId: 4,
    serviceCategoryId: 98,
    parentCatId: 97,
    isPartner: false,
    price: 150,
    deliveryPrice: 250,
    discount: 10,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 11,
    serviceName: 'โกนหนวด ตัดแต่งหนวด',
    shopId: 5,
    serviceCategoryId: 98,
    parentCatId: 97,
    isPartner: false,
    price: 150,
    deliveryPrice: 200,
    discount: 10,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 12,
    serviceName: 'ตัดผมชาย',
    shopId: 5,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: false,
    price: 180,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 13,
    serviceName: 'ตัดผม ทรงทันสมัย',
    shopId: 6,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: false,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 14,
    serviceName: 'โกนหนวด',
    shopId: 6,
    serviceCategoryId: 98,
    parentCatId: 97,
    isPartner: true,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 15,
    serviceName: 'ตัดผมเด็ก',
    shopId: 7,
    serviceCategoryId: 99,
    parentCatId: 97,
    isPartner: true,
    price: 250,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 16,
    serviceName: 'ออกแบบทรงผมท่านชาย',
    shopId: 7,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: true,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 17,
    serviceName: 'ตัดผมเด็ก',
    shopId: 8,
    serviceCategoryId: 99,
    parentCatId: 97,
    isPartner: true,
    price: 150,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 18,
    serviceName: 'ตัดผมท่านชาย',
    shopId: 8,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: true,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 19,
    serviceName: 'ตัดผมชาย',
    shopId: 9,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: false,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 20,
    serviceName: 'ตัดผมชาย',
    shopId: 10,
    serviceCategoryId: 101,
    parentCatId: 97,
    isPartner: false,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 21,
    serviceName: 'ตัดผมเด็ก',
    shopId: 10,
    serviceCategoryId: 99,
    parentCatId: 97,
    isPartner: false,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 22,
    serviceName: 'ไฮฟู',
    shopId: 11,
    serviceCategoryId: 103,
    parentCatId: 102,
    isPartner: false,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 23,
    serviceName: 'ไอพีแอล',
    shopId: 11,
    serviceCategoryId: 104,
    parentCatId: 102,
    isPartner: false,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 24,
    serviceName: 'โบท็อก',
    shopId: 11,
    serviceCategoryId: 105,
    parentCatId: 102,
    isPartner: false,
    price: 350,
    deliveryPrice: 400,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 25,
    serviceName: 'แพคเกจสำหรับการทำผม',
    shopId: 12,
    serviceCategoryId: 106,
    parentCatId: 102,
    isPartner: false,
    price: 350,
    deliveryPrice: 400,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 26,
    serviceName: 'แพ็คเกจทรีทเม้นท์ผิวหน้า',
    shopId: 12,
    serviceCategoryId: 107,
    parentCatId: 102,
    isPartner: false,
    price: 400,
    deliveryPrice: 450,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 27,
    serviceName: 'แต่งหน้า',
    shopId: 12,
    serviceCategoryId: 108,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 28,
    serviceName: 'เลเซอร์',
    shopId: 13,
    serviceCategoryId: 109,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 29,
    serviceName: 'เมโสแฟต',
    shopId: 13,
    serviceCategoryId: 110,
    parentCatId: 102,
    isPartner: false,
    price: 400,
    deliveryPrice: 450,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 30,
    serviceName: 'เมโส',
    shopId: 14,
    serviceCategoryId: 111,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 31,
    serviceName: 'เทอมาจ',
    shopId: 14,
    serviceCategoryId: 112,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 32,
    serviceName: 'อัลเทอร่า',
    shopId: 15,
    serviceCategoryId: 113,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 33,
    serviceName: 'รักษาสิว',
    shopId: 16,
    serviceCategoryId: 114,
    parentCatId: 102,
    isPartner: false,
    price: 450,
    deliveryPrice: 500,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 34,
    serviceName: 'ร้อยไหม',
    shopId: 16,
    serviceCategoryId: 115,
    parentCatId: 102,
    isPartner: false,
    price: 1000,
    deliveryPrice: 1200,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 35,
    serviceName: 'มาร์คหน้า',
    shopId: 17,
    serviceCategoryId: 116,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 590,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 36,
    serviceName: 'ฟิลเลอร์',
    shopId: 18,
    serviceCategoryId: 117,
    parentCatId: 102,
    isPartner: false,
    price: 550,
    deliveryPrice: 600,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 37,
    serviceName: 'ทรีตเม้นต์',
    shopId: 18,
    serviceCategoryId: 118,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 38,
    serviceName: 'ดูโอเยลโล่',
    shopId: 19,
    serviceCategoryId: 119,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 39,
    serviceName: 'ดูโอเยลโล่',
    shopId: 19,
    serviceCategoryId: 119,
    parentCatId: 102,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 40,
    serviceName: 'ทรีตเม้นต์',
    shopId: 20,
    serviceCategoryId: 118,
    parentCatId: 102,
    isPartner: false,
    price: 2500,
    deliveryPrice: 2600,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 41,
    serviceName: 'ฟิลเลอร์',
    shopId: 20,
    serviceCategoryId: 117,
    parentCatId: 102,
    isPartner: false,
    price: 250,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 42,
    serviceName: 'แต่งเล็บมือและเล็บเท้า',
    shopId: 21,
    serviceCategoryId: 62,
    parentCatId: 60,
    isPartner: false,
    price: 300,
    deliveryPrice: 400,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 43,
    serviceName: 'สปาเล็บเท้า',
    shopId: 21,
    serviceCategoryId: 63,
    parentCatId: 60,
    isPartner: false,
    price: 330,
    deliveryPrice: 400,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 44,
    serviceName: 'สปาเล็บมือ',
    shopId: 22,
    serviceCategoryId: 64,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 45,
    serviceName: 'บริการเพนท์เล็บ',
    shopId: 22,
    serviceCategoryId: 65,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 46,
    serviceName: 'บริการผลัดเซลล์ผิวส้นเท้า',
    shopId: 23,
    serviceCategoryId: 66,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 47,
    serviceName: 'บริการทรีทเม้นต์บำรุงเล็บ',
    shopId: 23,
    serviceCategoryId: 68,
    parentCatId: 60,
    isPartner: false,
    price: 150,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 48,
    serviceName: 'บริการต่อเล็บ pvc',
    shopId: 24,
    serviceCategoryId: 69,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 49,
    serviceName: 'บริการต่อเล็บ',
    shopId: 24,
    serviceCategoryId: 70,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 50,
    serviceName: 'บริการขัดเท้า',
    shopId: 25,
    serviceCategoryId: 71,
    parentCatId: 60,
    isPartner: false,
    price: 250,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 51,
    serviceName: 'ทำเล็บเจล',
    shopId: 25,
    serviceCategoryId: 72,
    parentCatId: 60,
    isPartner: false,
    price: 250,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 52,
    serviceName: 'ทำสีเล็บ',
    shopId: 26,
    serviceCategoryId: 73,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 53,
    serviceName: 'ทำเล็บเจล',
    shopId: 26,
    serviceCategoryId: 72,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 250,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 54,
    serviceName: 'ถอดเล็บต่อ',
    shopId: 27,
    serviceCategoryId: 74,
    parentCatId: 60,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 55,
    serviceName: 'ต่อเล็บอะคริลิก',
    shopId: 27,
    serviceCategoryId: 75,
    parentCatId: 60,
    isPartner: false,
    price: 600,
    deliveryPrice: 670,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 56,
    serviceName: 'ตกแต่งเล็บ',
    shopId: 28,
    serviceCategoryId: 76,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 57,
    serviceName: 'ถอดเล็บต่อ',
    shopId: 29,
    serviceCategoryId: 74,
    parentCatId: 60,
    isPartner: false,
    price: 200,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 58,
    serviceName: 'ต่อเล็บอะคริลิก',
    shopId: 29,
    serviceCategoryId: 75,
    parentCatId: 60,
    isPartner: false,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 59,
    serviceName: 'บริการขัดเท้า',
    shopId: 30,
    serviceCategoryId: 71,
    parentCatId: 60,
    isPartner: false,
    price: 250,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 60,
    serviceName: 'บริการผลัดเซลล์ผิวส้นเท้า',
    shopId: 30,
    serviceCategoryId: 66,
    parentCatId: 60,
    isPartner: false,
    price: 250,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 61,
    serviceName: 'นวดแผนไทย',
    shopId: 31,
    serviceCategoryId: 13,
    parentCatId: 5,
    isPartner: false,
    price: 250,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 62,
    serviceName: 'นวดอโรมา',
    shopId: 31,
    serviceCategoryId: 16,
    parentCatId: 5,
    isPartner: false,
    price: 350,
    deliveryPrice: 450,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 63,
    serviceName: 'นวดหน้า',
    shopId: 32,
    serviceCategoryId: 17,
    parentCatId: 5,
    isPartner: false,
    price: 200,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 64,
    serviceName: 'นวดศีรษะ',
    shopId: 32,
    serviceCategoryId: 19,
    parentCatId: 5,
    isPartner: false,
    price: 200,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 65,
    serviceName: 'นวดรีดเส้น',
    shopId: 33,
    serviceCategoryId: 20,
    parentCatId: 5,
    isPartner: false,
    price: 250,
    deliveryPrice: 400,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 66,
    serviceName: 'นวดมือ',
    shopId: 33,
    serviceCategoryId: 21,
    parentCatId: 5,
    isPartner: false,
    price: 250,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 67,
    serviceName: 'นวดบำบัด',
    shopId: 34,
    serviceCategoryId: 23,
    parentCatId: 5,
    isPartner: false,
    price: 500,
    deliveryPrice: 600,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 68,
    serviceName: 'นวดน้ำมัน',
    shopId: 34,
    serviceCategoryId: 24,
    parentCatId: 5,
    isPartner: false,
    price: 500,
    deliveryPrice: 550,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 69,
    serviceName: 'นวดกดจุด',
    shopId: 35,
    serviceCategoryId: 25,
    parentCatId: 5,
    isPartner: false,
    price: 500,
    deliveryPrice: 600,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 70,
    serviceName: 'นวดน้ำมัน',
    shopId: 35,
    serviceCategoryId: 24,
    parentCatId: 5,
    isPartner: false,
    price: 400,
    deliveryPrice: 500,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 71,
    serviceName: 'ซาวน่า',
    shopId: 36,
    serviceCategoryId: 26,
    parentCatId: 5,
    isPartner: false,
    price: 400,
    deliveryPrice: 450,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 72,
    serviceName: 'ชำระล้างร่างกาย',
    shopId: 36,
    serviceCategoryId: 27,
    parentCatId: 5,
    isPartner: false,
    price: 450,
    deliveryPrice: 500,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 73,
    serviceName: 'กระชับสัดส่วนด้วยการแรพ',
    shopId: 37,
    serviceCategoryId: 28,
    parentCatId: 5,
    isPartner: false,
    price: 1500,
    deliveryPrice: 1600,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 74,
    serviceName: 'นวดกดจุด',
    shopId: 38,
    serviceCategoryId: 25,
    parentCatId: 5,
    isPartner: false,
    price: 400,
    deliveryPrice: 500,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 75,
    serviceName: 'นวดน้ำมัน',
    shopId: 38,
    serviceCategoryId: 24,
    parentCatId: 5,
    isPartner: false,
    price: 450,
    deliveryPrice: 500,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 76,
    serviceName: 'นวดประคบ',
    shopId: 39,
    serviceCategoryId: 22,
    parentCatId: 5,
    isPartner: false,
    price: 350,
    deliveryPrice: 450,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 77,
    serviceName: 'นวดมือ',
    shopId: 39,
    serviceCategoryId: 21,
    parentCatId: 5,
    isPartner: false,
    price: 300,
    deliveryPrice: 350,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 78,
    serviceName: 'นวดประคบ',
    shopId: 39,
    serviceCategoryId: 22,
    parentCatId: 5,
    isPartner: false,
    price: 350,
    deliveryPrice: 400,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 79,
    serviceName: 'นวดศีรษะ',
    shopId: 40,
    serviceCategoryId: 19,
    parentCatId: 5,
    isPartner: false,
    price: 150,
    deliveryPrice: 200,
    isAtShop: true,
    isDelivery: true,
  ),
  ClientAppService(
    serviceId: 80,
    serviceName: 'นวดหน้า',
    shopId: 40,
    serviceCategoryId: 17,
    parentCatId: 5,
    isPartner: false,
    price: 250,
    deliveryPrice: 300,
    isAtShop: true,
    isDelivery: true,
  ),
];
